<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>vo</groupId>
	<artifactId>zrepository-starter</artifactId>
	<version>1.0.0-SNAPSHOT-jdk21</version>
	<name>zrepository-starter</name>
	<description>zrepository-starter</description>

	<properties>
		<java.version>21</java.version>
		<resource.delimiter>@</resource.delimiter>
		<maven.compiler.source>${java.version}</maven.compiler.source>
		<maven.compiler.target>${java.version}</maven.compiler.target>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8
		</project.reporting.outputEncoding>
	</properties>

	<dependencies>

		<dependency>
			<groupId>vo</groupId>
			<artifactId>zrepository</artifactId>
			<version>1.0.0-SNAPSHOT-jdk21</version>
		</dependency>

		<dependency>
			<groupId>vo</groupId>
			<artifactId>vortex-core</artifactId>
			<version>1.0.0-SNAPSHOT-jdk21</version>
		</dependency>

	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<source>21</source>
					<target>21</target>
					<compilerArgs>
						<arg>-parameters</arg>
					</compilerArgs>
					<parameters>true</parameters>
				</configuration>
			</plugin>
		</plugins>
	</build>

</project>
